### ISSUE TITLE
Needlessly patching Skyrim.esm records

### ISSUE THREAD

**Issue by reissue1426** [studioph/TofuPatcher#4]
This is with whitespace trim off. Don't think there is much point in patching QA books.
![image](https://github.com/user-attachments/assets/3c9e47f2-0c10-4eba-aab7-b4f13b1eda55)

**Comment by studioph** [comment]
The reason it's modifying those records is because the patcher looks at all record types that have display names. You are correct that touching these is unnecessary, but it's also harmless since you'll never see them in-game and there's only 3 of them (if it was hundreds of records that would be another story).

If other scenarios come to light where there is a single or small number of exceptional records that should be left alone (from a specific mod for instance), I will look at adding a record-level blacklist similar to the existing mod-level one, but since that comes with it's own issues it's not something I plan on doing just for this situation.
