### ISSUE TITLE
Trim Excess Whitespace results in empty dialogue options

### ISSUE THREAD

**Issue by reissue1426** [studioph/TofuPatcher#5]
With whitespace trim
![Screenshot 2024-11-16 234505](https://github.com/user-attachments/assets/404dfb01-3512-42f7-a9c0-0a744601d8fb)
Without whitespace trim
![Skyrim Special Edition GOG 16_11_2024 11_57_47 pm](https://github.com/user-attachments/assets/ab228994-fcd5-4d7c-8b08-7b5b2fedacd2)

This dialogue is from Maids II but I also saw it on other dialogue.

Found it in xedit but nothing looks off to me.
![image](https://github.com/user-attachments/assets/efce41dd-c00c-43ae-aba1-5ca99108bd75)

Might be related to the fact that the mod is using .STRINGS files?
![image](https://github.com/user-attachments/assets/77e08cc9-bc00-440a-a9b5-4ebbfe1a3094)

**Comment by studioph** [comment]
Thanks for reporting this! To clarify - this is the correct mod from the above screenshot: [Maids II - Deception](https://www.nexusmods.com/skyrimspecialedition/mods/189)?

**Comment by reissue1426** [comment]
Yep thats the one

**Comment by studioph** [comment]
So the interesting thing here is the Topic doesn't get touched at all by the patcher, which is shown in your screenshot - it's the 2nd response that is getting trimmed due to an extra space at the end.

~~What could be happening is the responses (which are being modified) now have the strings embedded in the plugin itself as opposed to being pulled from the strings file, but the topic is still trying to reference the strings file and there's a kind of mismatch there maybe. I'll have to keep investigating to see if my theory is correct.~~ Nevermind they're all embedded so it's not that.

Are there any other FormID examples you can give me that also exhibit this behavior in-game? Having multiple data points will help.

**Comment by studioph** [comment]
@reissue1426 Any chance of getting additional examples so I can continue investigating this? If you have any that aren't locked behind lots of quests or require lots of playtime to get to that would be preferable so that I can investigate in-game.

**Comment by studioph** [comment]
Closing for now due to lack of response and additional information to reproduce. Will open again if things change.

**Comment by reissue1426** [comment]
Sorry for taking a while to get back to you. Here is an example that should be easy to test:
![Skyrim Special Edition GOG 1_12_2024 8_04_05 pm](https://github.com/user-attachments/assets/aa52ad20-03d3-4e67-a2d9-7b501d73e2da)
This is from a new save using Immersive Speechcraft, More To Say, Conversations Raise Speechcraft, and Alternate Perspective. I just started in the Bannered Mare and walked around Whiterun until I found someone with broken dialogue.

**Comment by studioph** [comment]
No worries, thanks for getting back to me. I'll reopen and try to reproduce in my own game.

**Comment by studioph** [comment]
Ok I was able to quickly narrow down what I'm 99% certain is the cause - the `Prompt` field on the dialogue response records is getting accidentally set to an empty string instead of simply being left out in some cases. However, it only manifests if the response record is modified by the patcher, hence why turning off the trim whitespace setting "fixes" it.

If you're curious what I'm talking about - in the screenshots below, notice the (very subtle) coloring difference when it's an empty string vs not set.
![Screenshot_20241201_105911](https://github.com/user-attachments/assets/3fc50426-1e68-42b2-b0e5-53c16307b27b)
![Screenshot_20241201_110031](https://github.com/user-attachments/assets/aba828b0-a52e-4c3d-956a-ac22483c4fe2)

I'll publish an update shortly after I add some new test cases.

**Comment by studioph** [comment]
@reissue1426 I've pushed a new branch with some fixes. Would you mind running the patcher on the `Branch` setting with the value `5-trim-excess-whitespace-results-in-empty-dialogue-options` and confirm that it also fixes it for you? If so I'll go ahead and merge this and publish a new release for everyone downstream.

**Comment by reissue1426** [comment]
Yep that fixed it!

**Comment by studioph** [comment]
All merged - you can switch back to `LatestTag` (preferred) which should now be `v1.0.1` or `main`
